=== prasannaanubhav/Java-Web-Services-Part-1/XMLSchemaDemo/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.anubhav.com/Patient"
	xmlns:tns="http://www.anubhav.com/Patient"
	elementFormDefault="qualified">
	
	<element name="patient" type="tns:Patient"/>
	
	<complexType name="Patient">
	
	<sequence>
	<element name="id" type="tns:ID"/>
	<element name="name" type="string"/>
	<element name="age" type="int"/>
	<element name="dob" type="date"/>
	<element name="email" type="string"/>
	<element name="gender" type="tns:Gender"/>
	<element name="phone" type="tns:Phone"/>
	<element name="Payment" type="tns:Payment"/>
	</sequence>
	</complexType>
	
	<complexType name="Payment">
	<choice>
	<element name="cash" type="int"/>
	<element name="insurance" type="tns:Insurance"/>
	</choice>
	</complexType>
	
	<complexType name="Insurance">
	<all>
	<element name="provider" type="string"/>
	<element name = "limit" type="int"/>
	</all>
	
	</complexType>
	
	<simpleType name="ID">
	<restriction base="int">
	<pattern value="[0-9]*"/>
	</restriction>
	</simpleType>
	
	<simpleType name="Phone">
	<restriction base="string">
	<maxLength value="10"></maxLength>
	</restriction>
	</simpleType>
	
	<simpleType name="Gender">
	<restriction base="string">
	<enumeration value="M"/>
	<enumeration value="F"/>
	</restriction>
	</simpleType>
	
	
</schema>

=== prasannaanubhav/Java-Web-Services-Part-1/XMLSchemaDemo/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.anubhav.com/Patient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.anubhav.com/Patient Patient.xsd ">
  <tns:id>2</tns:id>
  <tns:name>Anubhav</tns:name>
  <tns:age>24</tns:age>
  <tns:dob>2001-01-01</tns:dob>
  <tns:email>prasanna.com</tns:email>
  <tns:gender>M</tns:gender>
  <tns:phone>1234567890</tns:phone>
  <tns:Payment>
    <tns:cash>25000</tns:cash>
  </tns:Payment>
</tns:patient>
